defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_dacer_agent.TrainDacerAgent

name: ${env_name}_dacer_mlp_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/walker2d-medium-v2_pre_diffusion_mlp_ta4_td20/2024-06-12_23-06-12/checkpoint/state_3000.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/normalization.npz
# offline_dataset_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/train.npz

seed: 42
device: cuda:0
env_name: halfcheetah-medium-v2
obs_dim: 17
action_dim: 6
denoising_steps: 20
ft_denoising_steps: 10
cond_steps: 1
horizon_steps: 1
act_steps: 1

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: sac-gym-${env_name}
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 1000
  # n_critic_warmup_itr: 0
  n_critic_warmup_itr: 5
  n_steps: 500
  gamma: 0.99
  actor_lr: 1e-4
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-4
  critic_lr: 1e-4
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-4
  # save_model_freq: 100000
  save_model_freq: 100
  # val_freq: 10000
  val_freq: 10
  render:
    freq: 1
    num: 0
  # log_freq: 200
  # SAC specific
  # batch_size: 256
  target_ema_rate: 0.005
  # scale_reward_factor: 1
  scale_reward_factor: 0.01
  critic_replay_ratio: 256
  actor_replay_ratio: 128
  # buffer_size: 1000000
  buffer_size: 25000 # * n_envs
  n_eval_episode: 10
  n_explore_steps: 5000
  target_entropy: ${eval:'- ${action_dim} * ${act_steps}'}
  init_temperature: 0.272
  eval_sample_num: 20 # how many samples to score during eval
  critic_tau: 0.001  # rate of target q network update
  use_expectile_exploration: True
  replay_ratio: 128
  batch_size: 256

model:
  _target_: model.diffusion.diffusion_DACER.DACER_Diffusion
  randn_clip_value: 10
  tanh_output: True # squash after sampling

  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic: # no layernorm
    _target_: model.common.critic.CriticObsAct_DACER
    mlp_dims: [256, 256, 256]
    activation_type: GELU
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    action_dim: ${action_dim}
    action_steps: ${act_steps}
  ft_denoising_steps: ${ft_denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
  